### ISSUE TITLE
TOC for a page

### ISSUE THREAD

**Issue by amitavroy** [ijpatricio/wikicenter#7]
## Requirement
As a content creator I should be able to create a TOC for the page content. A reader should be able to quickly scan the TOC and click on individual sections to quickly jump to that content.

## Technical implementation
1. To have a TOC for a page which can be clicked and viewed, we should add an additional field to the Content tip tap component called "Content title" or something. 
1. When rendering the content on a page, we will then scan all the Content tip tap component blocks and render the TOC on top of the page. 
1. And, we can also add anchor links to this which will allow us to allow user to navigate to that section.

**Comment by amitavroy** [comment]
@ijpatricio let me know your thoughts

**Comment by ijpatricio** [comment]
It's just like we spoke on the call, beautiful 👌

Thanks!
